'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import 'bootstrap/dist/css/bootstrap.css'
import { store } from './redux-toolkit/store/store'
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          {/* <Header /> */}
          {children}
          {/* <Footer /> */}
        </Provider>
      </body>
    </html>
  );
}
