'use client'
import React, { useState } from 'react'
import Head from 'next/head'

export default function Home() {
  const [fname, setFname] = useState('')
  const [lname, setLname] = useState('')
  const [email, setEmail] = useState('')
  const [address1, setAddress1] = useState('')
  const [address2, setAddress2] = useState('')
  const [state, setState] = useState('')
  const [zip, setZip] = useState('')
  const [country, setCountry] = useState('India')
  const [dob, setDob] = useState('')
  const [gender, setGender] = useState('male')
  const [countryCode, setCountryCode] = useState('91')
  const [phone, setPhone] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [terms, setTerms] = useState(false)

  const handleSubmit = (e) => {
    e.preventDefault()

    // Basic validation (replace with your preferred validation logic)
    if (password !== confirmPassword) {
      alert('Passwords do not match!')
      return
    }

    // Submit the form data (replace with your API call)
    console.log({
      fname,
      lname,
      email,
      address1,
      address2,
      state,
      zip,
      country,
      dob,
      gender,
      countryCode,
      phone,
      password,
    })
  }

  return (
    <>
      <Head>
        <title>Registration Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mt-3">
        <form onSubmit={handleSubmit}>
          <div className="row jumbotron box8">
            <div className="col-sm-12 mx-t3 mb-4">
              <h2 className="text-center text-info">Register</h2>
            </div>
            <div className="col-sm-6 form-group">
              <label htmlFor="name-f">First Name</label>
              <input
                type="text"
                className="form-control"
                name="fname"
                id="name-f"
                placeholder="Enter your first name."
                required
                value={fname}
                onChange={(e) => setFname(e.target.value)}
              />
            </div>
            <div className="col-sm-6 form-group">
              <label htmlFor="name-l">Last name</label>
              <input
                type="text"
                className="form-control"
                name="lname"
                id="name-l"
                placeholder="Enter your last name."
                required
                value={lname}
                onChange={(e) => setLname(e.target.value)}
              />
            </div>
            <div className="col-sm-6 form-group">
              <label htmlFor="email">Email</label>
              <input
                type="email"
                className="form-control"
                name="email"
                id="email"
                placeholder="Enter your email."
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <div className="col-sm-6 form-group">
              <label htmlFor="address-1">Address Line-1</label>
              <input
                type="text"
                className="form-control"
                name="Locality"
                id="address-1"
                placeholder="Locality/House/Street no."
                required
                value={address1}
                onChange={(e) => setAddress1(e.target.value)}
              />
            </div>
            <div className="col-sm-6 form-group">
              <label htmlFor="address-2">Address Line-2</label>
              <input
                type="text"
                className="form-control"
                name="address"
                id="address-2"
                placeholder="Village/City Name."
                required
                value={address2}
                onChange={(e) => setAddress2(e.target.value)}
              />
            </div>
            <div className="col-sm-4 form-group">
              <label htmlFor="State">State</label>
              <input
                type="text"
                className="form-control"
                name="State"
                id="State"
                placeholder="Enter your state name."
                required
                value={state}
                onChange={(e) => setState(e.target.value)}
              />
            </div>
            <div className="col-sm-2 form-group">
              <label htmlFor="zip">Postal-Code</label>
              <input
                type="text"
                className="form-control"
                name="Zip"
                id="zip"
                placeholder="Postal-Code."
                required
                value={zip}
                onChange={(e) => setZip(e.target.value)}
              />
            </div>
            <div className="col-sm-6 form-group">
              <label htmlFor="Country">Country</label>
              <select
                className="form-control custom-select browser-default"
                id="Country"
                value={country}
                onChange={(e) => setCountry(e.target.value)}
              >
                {/* Add more country options */}
                <option value="India">India</option>
                <option value="United States">United States</option>
              </select>
            </div>
            <div className="col-sm-6 form-group">
              <label htmlFor="Date">Date Of Birth</label>
              <input
                type="date"
                name="dob"
                className="form-control"
                id="Date"
                placeholder=""
                required
                value={dob}
                onChange={(e) => setDob(e.target.value)}
              />
            </div>
            <div className="col-sm-6 form-group">
              <label htmlFor="sex">Gender</label>
              <select
                id="sex"
                className="form-control browser-default custom-select"
                value={gender}
                onChange={(e) => setGender(e.target.value)}
              >
                <option value="male">Male</option>
                <option value="female">Female</option>
                <option value="unspesified">Unspecified</option>
              </select>
            </div>
            <div className="col-sm-2 form-group">
              <label htmlFor="cod">Country code</label>
              <select
                className="form-control browser-default custom-select"
                id="cod"
                value={countryCode}
                onChange={(e) => setCountryCode(e.target.value)}
              >
                <option data-countryCode="IN" value="91" selected>
                  India (+91)
                </option>
                <option data-countryCode="US" value="1">
                  USA (+1)
                </option>
                {/* Add more country code options */}
              </select>
            </div>
            <div className="col-sm-4 form-group">
              <label htmlFor="tel">Phone</label>
              <input
                type="tel"
                name="phone"
                className="form-control"
                id="tel"
                placeholder="Enter Your Contact Number."
                required
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
              />
            </div>
            <div className="col-sm-6 form-group">
              <label htmlFor="pass">Password</label>
              <input
                type="password"
                name="password"
                className="form-control"
                id="pass"
                placeholder="Enter your password."
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>
            <div className="col-sm-6 form-group">
              <label htmlFor="pass2">Confirm Password</label>
              <input
                type="password"
                name="cnf-password"
                className="form-control"
                id="pass2"
                placeholder="Re-enter your password."
                required
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
              />
            </div>
            <div className="col-sm-12">
              <input
                type="checkbox"
                className="form-check d-inline"
                id="chb"
                required
                checked={terms}
                onChange={(e) => setTerms(e.target.checked)}
              />
              <label htmlFor="chb" className="form-check-label">
                &nbsp;I accept all terms and conditions.
              </label>
            </div>
            <div className="col-sm-12 form-group mb-0">
              <button type="submit" className="btn btn-primary float-right">
                Submit
              </button>
            </div>
          </div>
        </form>
      </main>
    </>
  )
}
